# Generated by Django 4.1 on 2022-08-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('adrres', models.CharField(max_length=70)),
                ('acomps', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
