# Generated by Django 4.1 on 2022-10-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('device', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50)),
                ('qnty', models.IntegerField(default=1)),
                ('item', models.CharField(max_length=100)),
                ('acomps', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('observation', models.CharField(blank=True, max_length=250)),
                ('acomps_1', models.CharField(max_length=100)),
                ('acomps_2', models.CharField(blank=True, max_length=100)),
                ('acomps_3', models.CharField(blank=True, max_length=100)),
                ('acomps_4', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Not Confirmed', 'Not Confirmed'), ('Confirmed', 'Confirmed'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Not Confirmed', max_length=150, null=True)),
                ('items', models.ManyToManyField(related_name='item_orders', to='cart.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.quentinha')),
            ],
        ),
    ]
