# Generated by Django 4.1 on 2022-08-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0026_order_acompanhamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adrres', models.CharField(max_length=70)),
                ('orders', models.ManyToManyField(to='products.order')),
            ],
        ),
    ]
