# Generated by Django 4.1 on 2022-08-29 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_orders_cart_acomps_cart_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_created',
        ),
    ]
