# Generated by Django 4.1 on 2022-09-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_adrres_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_name',
        ),
    ]
