# Generated by Django 4.1 on 2022-09-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='observation',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
