# Generated by Django 4.1 on 2022-09-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='acomps_1',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='acomps_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='acomps_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='acomps_4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
