# Generated by Django 4.1 on 2022-09-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_quentinha_acompanhamentos'),
        ('cart', '0009_remove_order_acompanhamentos_order_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='acomps',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='acomps_1',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='acomps_2',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='acomps_3',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='acomps_4',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.quentinha'),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='acomps',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='acomps_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='acomps_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='acomps_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='acomps_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='observation',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
