# Generated by Django 4.1 on 2022-09-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_remove_cart_acomps_remove_cart_acomps_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='acomps',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='acomps_1',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='acomps_2',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='acomps_3',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='acomps_4',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='idn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
