# Generated by Django 4.1 on 2022-09-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_order_acompanhamentos_remove_order_idn'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qnty',
            field=models.IntegerField(default=1),
        ),
    ]
