# Generated by Django 4.1 on 2022-10-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_customer_remove_order_acompanhamentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='acomps',
        ),
    ]
