# Generated by Django 4.1 on 2022-10-04 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_quentinha_acompanhamentos'),
        ('cart', '0017_remove_order_acomps'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_ordered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.quentinha'),
        ),
    ]
