# Generated by Django 4.1 on 2022-10-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_order_item_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
    ]
