# Generated by Django 4.1 on 2022-10-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_customer_payment_alter_cart_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart_activity',
            field=models.ManyToManyField(to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
