# Generated by Django 4.1 on 2022-10-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_customer_cart_activity_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment',
            field=models.CharField(choices=[('D', 'Dinheiro'), ('CD', 'Cartão de Debito'), ('CC', 'Cartão de Crédito')], max_length=10),
        ),
    ]
