# Generated by Django 4.1 on 2022-10-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_bebidas_choices'),
        ('cart', '0023_remove_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bebida_choices',
            field=models.ManyToManyField(blank=True, null=True, to='products.bebida'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_ordered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.quentinha'),
        ),
    ]
