# Generated by Django 4.1 on 2022-10-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_bebidas_choices'),
        ('cart', '0024_cart_bebida_choices_alter_order_item_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='bebida_choices',
            field=models.ManyToManyField(blank=True, to='products.bebida'),
        ),
    ]
