# Generated by Django 4.1 on 2022-08-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_acompanhamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='acompanhamentos',
            field=models.BooleanField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')]),
        ),
    ]
