# Generated by Django 4.1 on 2022-08-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_extra_delete_acomp_remove_order_acompanhamentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feijoada',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='quentinha',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
