# Generated by Django 4.1 on 2022-08-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_acompanhamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quentinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('price', models.FloatField()),
                ('acompanhamentos', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
