# Generated by Django 4.1 on 2022-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_feijoada_thumb_quentinha_thumb_alter_bebida_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentos',
            name='acomp_choices',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
