# Generated by Django 4.1 on 2022-08-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_quentinha_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feijoada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('price', models.FloatField()),
                ('acompanhamentos', models.BooleanField(default=False)),
                ('extras', models.BooleanField(default=True)),
            ],
        ),
    ]
