# Generated by Django 4.1 on 2022-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_acompanhamentos_acomp_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentos',
            name='acomp_choices',
            field=models.CharField(blank=True, default=True, max_length=50),
            preserve_default=False,
        ),
    ]
