# Generated by Django 4.1 on 2022-08-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_bebida'),
    ]

    operations = [
        migrations.AddField(
            model_name='quentinha',
            name='xxx',
            field=models.BooleanField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default=True),
            preserve_default=False,
        ),
    ]
