# Generated by Django 4.1 on 2022-09-18 21:18

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_acompanhamentos_acomp_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', multiselectfield.db.fields.MultiSelectField(choices=[('arroz_branco', 'Arroz Branco'), ('macarrao', 'Macarrão'), ('feijao_preto', 'Feijão Preto'), ('feijao_caseiro', 'Feijão Caseiro'), ('maionese', 'Maionese')], max_length=20)),
            ],
        ),
    ]
