# Generated by Django 4.1 on 2022-09-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
