# Generated by Django 4.1 on 2022-08-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_quentinha_xxx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quentinha',
            name='xxx',
        ),
        migrations.AlterField(
            model_name='quentinha',
            name='acompanhamentos',
            field=models.BooleanField(choices=[('arroz', 'Arroz Branco'), ('macarrao', 'Macarrao'), ('pure', 'Pure'), ('feijao_preto', 'Feijão Preto'), ('feijao_caseiro', 'Feijão Caseiro')]),
        ),
    ]
