# Generated by Django 4.1 on 2022-09-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_mymodel'),
    ]

    operations = [
    ]
