# Generated by Django 4.1 on 2022-08-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_quentinha_xxx_alter_quentinha_acompanhamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feijoada',
            name='extras',
        ),
        migrations.AddField(
            model_name='feijoada',
            name='testando',
            field=models.CharField(choices=[('ARROZ', 'Arroz'), ('FEIJAO', 'Feijao')], default=True, max_length=10),
            preserve_default=False,
        ),
    ]
