# Generated by Django 4.1 on 2022-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_feijoada_extras_feijoada_testando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feijoada',
            name='testando',
            field=models.BooleanField(choices=[('ARROZ', 'Arroz branco'), ('FEIJAO', 'Feijao preto'), ('MACARRAO', 'Macarrao')]),
        ),
    ]
