# Generated by Django 4.1 on 2022-10-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_quentinha_acompanhamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebidas_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=50)),
            ],
        ),
    ]
