# Generated by Django 4.1 on 2022-10-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_bebidas_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bebidas_choices',
        ),
        migrations.AlterField(
            model_name='quentinha',
            name='acompanhamentos',
            field=models.ManyToManyField(blank=True, to='products.acompanhamentos'),
        ),
    ]
