# Generated by Django 4.1 on 2022-08-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_feijoada_testando'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feijoada',
            old_name='acompanhamentos',
            new_name='extras',
        ),
        migrations.AlterField(
            model_name='feijoada',
            name='testando',
            field=models.CharField(choices=[('ARROZ', 'Arroz branco'), ('FEIJAO', 'Feijao preto'), ('MACARRAO', 'Macarrao')], max_length=15),
        ),
    ]
