# Generated by Django 4.1 on 2022-08-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_acompanhamentos_feijoada_extras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quentinha',
            name='acompanhamentos',
            field=models.BooleanField(choices=[('arroz', 'Arroz Branco'), ('macarrao', 'Macarrao'), ('pure', 'Pure'), ('feijao_preto', 'Feijão Preto'), ('feijao_caseiro', 'Feijão Caseiro')], default=False),
        ),
    ]
