# Generated by Django 4.1 on 2022-08-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_quentinha_acompanhamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('price', models.FloatField()),
                ('acompanhamentos', models.BooleanField(choices=[('arroz', 'Arroz Branco'), ('macarrao', 'Macarrao'), ('pure', 'Pure'), ('feijao_preto', 'Feijão Preto'), ('feijao_caseiro', 'Feijão Caseiro')], default=False)),
            ],
        ),
    ]
