# Generated by Django 4.1 on 2022-08-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='acompanhamentos',
        ),
    ]
