# Generated by Django 4.1 on 2022-08-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_acompanhamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feijoada',
            name='testando',
        ),
        migrations.RemoveField(
            model_name='quentinha',
            name='acompanhamentos',
        ),
    ]
