# Generated by Django 4.1 on 2022-08-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_acompanhamentos_quentinha_acompanhamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('adress', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='acompanhamentos',
            name='acomp_choices',
            field=models.BooleanField(choices=[('ARROZ_BRANCO', 'Arroz'), ('MACARRAO', 'macarrao'), ('FEIJAO_PRETO', 'feijao')], default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quentinha',
            name='acompanhamentos',
            field=models.BooleanField(default=False),
        ),
    ]
