# Generated by Django 4.1 on 2022-08-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_acompanhamentos_acomp_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentos',
            name='acomp_choices',
            field=models.CharField(max_length=50),
        ),
    ]
