# Generated by Django 4.1 on 2022-08-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quentinha',
            name='acompanhamentos',
        ),
        migrations.AddField(
            model_name='quentinha',
            name='acompanhamentos',
            field=models.ManyToManyField(to='products.acompanhamentos'),
        ),
    ]
