# Generated by Django 4.1 on 2022-08-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_acomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomp',
            name='acomps',
            field=models.CharField(choices=[('ARROZ_BRANCO', 'Arroz Branco'), ('MACARRAO', 'Macarrão'), ('FEIJAO_PRETO', 'Feijão Preto')], default='MACARRAO', max_length=15),
        ),
    ]
