# Generated by Django 4.1 on 2022-08-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_acomp_acomps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quentinha',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=4),
            preserve_default=False,
        ),
    ]
